---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-proxy-cm
  namespace: "yrt"
data:
  default: |
    server {
      listen 80;

      location / {
        proxy_pass http://srv-back:9003;
      }
    }