---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-front
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-proxy
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-proxy
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-proxy
    spec:
      containers:
      - name: {{ .Chart.Name }}-nginx-proxy
        image: lerenn/nginx-reverse-proxy
        imagePullPolicy: IfNotPresent
        ports:
        - name: web
          containerPort: 80
        volumeMounts:
        - name: nginx-proxy
          mountPath: /etc/nginx/sites-available
      restartPolicy: Always
      volumes:
      - name: nginx-proxy
        configMap:
          name: nginx-proxy-cm