apiVersion: v1
kind: Service
metadata:
  name: srv-back
  namespace: {{ .Release.Namespace }}
  labels:
    env : dev
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Release.Name }}-webapp
